resume:
pretrain: 
seed: 1024
data:
    dataset: k400
    modality: RGB
    num_segments: 16
    seg_length: 1
    batch_size: 16
    test_batch_size: 8
    workers: 4
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_root: '/home/mjkim/datasets/k400/train'
    train_list: 'lists/k400/train_rgb.txt'
    val_root: '/home/mjkim/datasets/k400/val'
    val_list: lists/k400/val_rgb.txt
    label_list: 'lists/kinetics_400_labels.csv'
    input_size: 224
    random_shift: True
    num_sample: 1
    rand_aug: False
    rand_erase: False
network:
    arch: MAE-ViT-B-16  #ViT-B/32 ViT-B/16
    init: True
    tm: False # localuni t1d atm False
    dropout: 0.0
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: None  # Transf   None  
    joint_st: False
    drop_fc: 0     
    n_emb: 320
    side_dim: 320
    corr_layer_index: [3]
    corr_dim: 128
    corr_func: "cosine" # 'cosine', 'dotproduct_softmax'
    corr_window: [5, 9, 9]
    corr_ext_chnls: [64]
    corr_int_chnls: [64, 64, 128]
    corr_num_encoders: 2
    fix_clip: False 
    my_fix_clip: True
    sync_bn: False
    num_checkpoints: 6
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 1.e-3
    warmup_lr: 1.e-6
    lr_warmup_step: 4
    final_factor: 0.01
    weight_decay: 0.15
    loss_type: CE
    evaluate: False
    betas: [0.9, 0.999]
    clip_ratio: 1
    grad_accumulation_steps: 1  
    smoothing: 0.1
    layer_decay: 1.0 # 0.7
logging:
    print_freq: 10
    eval_freq: 2
    skip_epoch: []
    acc_per_class: True
    correct_per_sample: True
wandb:
    use_wandb: True
    entity: mandos
    key: "5663c183a53a252ec9b39f4816e68bfe70f72107"
    project_name: "corr_adapter_k400"
    exp_name: "default"
    group_name: None